steps:
- id: 'tf plan'
  name: 'hashicorp/terraform:1.0.0'
    
  script: |
          echo ""
          echo "*************** TERRAFOM PLAN ******************"
          
          echo "*************************************************"
          terraform init
          terraform plan --var-file variables.tf
         
options:
  logging: CLOUD_LOGGING_ONLY
